from enum import Enum


class DecisionInsightMotivesItem(str, Enum):
    BATTERY_CHARGE_SURPLUS_TO_COVER_LOAD = "BATTERY_CHARGE_SURPLUS_TO_COVER_LOAD"
    BATTERY_CHARGE_SURPLUS_TO_DISCHARGE_TO_GRID = "BATTERY_CHARGE_SURPLUS_TO_DISCHARGE_TO_GRID"
    BATTERY_CHARGE_TO_COVER_LOAD = "BATTERY_CHARGE_TO_COVER_LOAD"
    BATTERY_CHARGE_TO_DISCHARGE_TO_GRID = "BATTERY_CHARGE_TO_DISCHARGE_TO_GRID"
    BATTERY_DISCHARGE_TO_GRID = "BATTERY_DISCHARGE_TO_GRID"
    BATTERY_KEEP_TO_COVER_LOAD = "BATTERY_KEEP_TO_COVER_LOAD"
    BATTERY_KEEP_TO_DISCHARGE_TO_GRID = "BATTERY_KEEP_TO_DISCHARGE_TO_GRID"
    EV_CHARGE_IN_LOW_PRICES = "EV_CHARGE_IN_LOW_PRICES"
    EV_CHARGE_TO_SATISFY_DESIRED_SOC = "EV_CHARGE_TO_SATISFY_DESIRED_SOC"
    EV_DELAY_CHARGE_TO_LOW_PRICES = "EV_DELAY_CHARGE_TO_LOW_PRICES"
    EV_DELAY_CHARGE_TO_SURPLUS = "EV_DELAY_CHARGE_TO_SURPLUS"
    EV_KEEP_TO_EXPORT_SURPLUS_AND_CHARGE_FROM_GRID_LATER = "EV_KEEP_TO_EXPORT_SURPLUS_AND_CHARGE_FROM_GRID_LATER"
    HEAT_PUMP_RECOMMEND_ON_MOTIVE = "HEAT_PUMP_RECOMMEND_ON_MOTIVE"

    def __str__(self) -> str:
        return str(self.value)
