from enum import Enum


class GetSystemsSystemIDTimeofuseDecisionsResponse200DecisionsItemCaseName(str, Enum):
    BATTERY_CHARGE_FROM_GRID = "BATTERY_CHARGE_FROM_GRID"
    BATTERY_CHARGE_FROM_SURPLUS = "BATTERY_CHARGE_FROM_SURPLUS"
    BATTERY_DISCHARGE_TO_GRID = "BATTERY_DISCHARGE_TO_GRID"
    BATTERY_LIMIT_CHARGE = "BATTERY_LIMIT_CHARGE"
    BATTERY_LIMIT_DISCHARGE = "BATTERY_LIMIT_DISCHARGE"
    BATTERY_NO_CHARGE = "BATTERY_NO_CHARGE"
    BATTERY_NO_CHARGE_NO_DISCHARGE = "BATTERY_NO_CHARGE_NO_DISCHARGE"
    BATTERY_NO_DISCHARGE = "BATTERY_NO_DISCHARGE"
    BATTERY_SELF_CONSUMPTION = "BATTERY_SELF_CONSUMPTION"
    BATTERY_UNDEFINED_DECISION = "BATTERY_UNDEFINED_DECISION"
    EV_CHARGE_FROM_GRID = "EV_CHARGE_FROM_GRID"
    EV_LIMIT_CHARGE = "EV_LIMIT_CHARGE"
    EV_LIMIT_DISCHARGE = "EV_LIMIT_DISCHARGE"
    EV_NO_CHARGE = "EV_NO_CHARGE"
    EV_NO_DECISION = "EV_NO_DECISION"
    EV_UNDEFINED_DECISION = "EV_UNDEFINED_DECISION"
    HEATPUMP_AUTO = "HEATPUMP_AUTO"
    HEATPUMP_RECOMMEND_ON = "HEATPUMP_RECOMMEND_ON"
    PV_CURTAILMENT = "PV_CURTAILMENT"
    PV_NO_DECISION = "PV_NO_DECISION"

    def __str__(self) -> str:
        return str(self.value)
