from enum import Enum


class GetSystemsSystemIDTimeofuseStatusResponse200PeriodsItemErrorCode(str, Enum):
    EMS_CONSENT_NOT_GIVEN = "EMS_CONSENT_NOT_GIVEN"
    EMS_NOT_ENABLED = "EMS_NOT_ENABLED"
    INCOMPLETE_PRICES = "INCOMPLETE_PRICES"
    INTERNAL_ERROR = "INTERNAL_ERROR"
    MISSING_APPLIANCES = "MISSING_APPLIANCES"
    MISSING_CONTROLLABLE_APPLIANCE = "MISSING_CONTROLLABLE_APPLIANCE"
    MISSING_FUSE_IMPORT_LIMIT = "MISSING_FUSE_IMPORT_LIMIT"
    MISSING_GRID_METER = "MISSING_GRID_METER"
    MISSING_HISTORICAL_DATA = "MISSING_HISTORICAL_DATA"
    MISSING_PRICES = "MISSING_PRICES"
    MULTIPLE_BATTERIES = "MULTIPLE_BATTERIES"
    MULTIPLE_EVCS = "MULTIPLE_EVCS"
    MULTIPLE_GRID_METERS = "MULTIPLE_GRID_METERS"
    MULTIPLE_HEAT_PUMPS = "MULTIPLE_HEAT_PUMPS"
    MULTIPLE_PVS_CURTAILMENT = "MULTIPLE_PVS_CURTAILMENT"
    OFFLINE_APPLIANCE = "OFFLINE_APPLIANCE"
    PV_CURTAILMENT_NOT_SUPPORTED = "PV_CURTAILMENT_NOT_SUPPORTED"
    STATIC_PRICES = "STATIC_PRICES"
    UNKNOWN_INVERTER = "UNKNOWN_INVERTER"

    def __str__(self) -> str:
        return str(self.value)
