from enum import Enum


class HardwareStatusDescription(str, Enum):
    BATTERY_FAULT = "BATTERY_FAULT"
    COMMUNICATION_FAULT = "COMMUNICATION_FAULT"
    DC_OVERCURRENT = "DC_OVERCURRENT"
    FAN_FAULT = "FAN_FAULT"
    GRID_FAULT = "GRID_FAULT"
    HARDWARE_FAULT = "HARDWARE_FAULT"
    HIGH_DC_VOLTAGE = "HIGH_DC_VOLTAGE"
    HIGH_TEMPERATURE = "HIGH_TEMPERATURE"
    INSTALLATION_FAULT = "INSTALLATION_FAULT"
    INSULATION_FAILURE = "INSULATION_FAILURE"
    INTERFERENCE_DEVICE = "INTERFERENCE_DEVICE"
    LOW_DC_POWER = "LOW_DC_POWER"
    OTHER = "OTHER"
    PARAMETER_FAULT = "PARAMETER_FAULT"
    SOFTWARE_FAULT = "SOFTWARE_FAULT"
    WAIT_FOR_UPDATE = "WAIT_FOR_UPDATE"

    def __str__(self) -> str:
        return str(self.value)
