from enum import Enum


class ToUWarningsItem(str, Enum):
    MISSING_EV_CONFIG = "MISSING_EV_CONFIG"
    MISSING_EV_PROFILE = "MISSING_EV_PROFILE"
    UNSUPPORTED_CHARGE_MODE_QUICK = "UNSUPPORTED_CHARGE_MODE_QUICK"
    UNSUPPORTED_CHARGE_MODE_SAFETY = "UNSUPPORTED_CHARGE_MODE_SAFETY"
    UNSUPPORTED_CHARGE_MODE_SURPLUS = "UNSUPPORTED_CHARGE_MODE_SURPLUS"
    UNSUPPORTED_CHARGE_MODE_UNKNOWN = "UNSUPPORTED_CHARGE_MODE_UNKNOWN"

    def __str__(self) -> str:
        return str(self.value)
