from enum import Enum


class ToUReadinessReason(str, Enum):
    SYSTEM_LOCATION_MISSING = "SYSTEM_LOCATION_MISSING"
    TARIFF_PRICES_BIDDING_ZONE_NOT_SET = "TARIFF_PRICES_BIDDING_ZONE_NOT_SET"
    TARIFF_PRICES_NOT_DYNAMIC = "TARIFF_PRICES_NOT_DYNAMIC"
    TARIFF_PRICES_NOT_SET = "TARIFF_PRICES_NOT_SET"
    UNKNOWN_REASON = "UNKNOWN_REASON"
    UNSUPPORTED_APPLIANCE_BATTERY_INVERTER = "UNSUPPORTED_APPLIANCE_BATTERY_INVERTER"
    UNSUPPORTED_APPLIANCE_EVCS = "UNSUPPORTED_APPLIANCE_EVCS"
    UNSUPPORTED_APPLIANCE_HEAT_PUMP = "UNSUPPORTED_APPLIANCE_HEAT_PUMP"
    UNSUPPORTED_APPLIANCE_PV_INVERTER = "UNSUPPORTED_APPLIANCE_PV_INVERTER"
    UNSUPPORTED_SETUP_MULTIPLE_BATTERIES = "UNSUPPORTED_SETUP_MULTIPLE_BATTERIES"
    UNSUPPORTED_SETUP_MULTIPLE_EVCS = "UNSUPPORTED_SETUP_MULTIPLE_EVCS"
    UNSUPPORTED_SETUP_MULTIPLE_GRID_METERS = "UNSUPPORTED_SETUP_MULTIPLE_GRID_METERS"
    UNSUPPORTED_SETUP_MULTIPLE_HEAT_PUMPS = "UNSUPPORTED_SETUP_MULTIPLE_HEAT_PUMPS"
    UNSUPPORTED_SETUP_NO_APPLIANCES_FOUND = "UNSUPPORTED_SETUP_NO_APPLIANCES_FOUND"
    UNSUPPORTED_SETUP_NO_CONTROLLABLE_APPLIANCE = "UNSUPPORTED_SETUP_NO_CONTROLLABLE_APPLIANCE"
    UNSUPPORTED_SETUP_NO_GRID_METER = "UNSUPPORTED_SETUP_NO_GRID_METER"
    UNSUPPORTED_SETUP_UNKNOWN_APPLIANCE = "UNSUPPORTED_SETUP_UNKNOWN_APPLIANCE"

    def __str__(self) -> str:
        return str(self.value)
