name: Version Workflow

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Select the version type'
                required: true
                type: choice
                default: 'patch'
                options:
                    - major
                    - minor
                    - patch
                    - dev

jobs:
    build:
        runs-on: ubuntu-latest
        permissions:
          contents: write
        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Install uv
              uses: astral-sh/setup-uv@v4

            - name: Set old version
              run: echo "OLD_VERSION=$(uvx bump-my-version show current_version)" >> $GITHUB_ENV

            - name: Bump version
              run: uvx bump-my-version bump ${{ github.event.inputs.version }}

            - name: Set new version
              run: echo "TAG_NAME=$(uvx bump-my-version show current_version)" >> $GITHUB_ENV

            - name: Commit and tag
              uses: stefanzweifel/git-auto-commit-action@v5
              with:
                tagging_message: v${{ env.TAG_NAME }}
                commit_message: "Bump version: ${{ env.OLD_VERSION }} -> ${{ env.TAG_NAME }}"
